const errorMapping = {
    VALIDATION_ERROR: 1,
    USER_NOT_FOUND: 2,
    INVALID_ROLE: 3,
    INSUFFICIENT_PERMISSIONS: 4,
    INVALID_USERS_CREDENTIALS: 5,
    INVALID_USER_PASSWORD: 6,
    PASSWORDS_NOT_MATCHED: 7,
    CONFLICT_DUPLICATE_KEY_ERROR: 8,
    INVALID_EMAIL_TYPE: 9,
    API_ENDPOINT_NOT_FOUND: 10,
    USER_NOT_VERIFIED: 11,
    INVALID_TOKEN: 12,
    FORBIDDEN_RESOURCE: 13,
    INVALID_REFRESH_TOKEN: 14
};

export default errorMapping;

